build site:
  image: node:14
  stage: build
  script:
    - yarn install
    - yarn serve
  artifacts:
    expire_in: 1 week
    paths:
      - dist

unit test:
  image: node:14
  stage: test
  script:
    - yarn install
    - yarn test
